name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  NODE_VERSION: '24.x'

jobs:
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Import macOS signing cert
        run: |
          echo "${{ secrets.MAC_CERTIFICATE }}" | base64 --decode > mac_cert.p12
          security create-keychain -p "" build.keychain
          security import mac_cert.p12 \
            -k build.keychain \
            -P "${{ secrets.MAC_CERTIFICATE_PASSWORD }}" \
            -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain
      - name: Build & notarize macOS (arm64)
        env:
          CSC_LINK: mac_cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run dist:mac

      # build intel
      - name: Build & notarize macOS (Intel x64)
        env:
          CSC_LINK: mac_cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run dist:mac:intel

      # rename the intel build
      - name: Rename Intel macOS artifacts
        run: |
          for file in dist/*.dmg dist/*.zip; do
            if [[ "$file" == *x64* || "$file" == *"mac"* ]]; then
              base=$(basename "$file")
              ext="${base##*.}"
              if [[ ! "$base" =~ "intel" ]]; then
                mv "$file" "dist/Wing-to-LiveTrax-${{ github.ref_name }}-mac-intel.$ext"
              fi
            fi
          done

      # copy to artifacts
      - name: Copy macOS builds to artifacts
        run: |
          mkdir -p artifacts/macOS
          cp dist/*.dmg artifacts/macOS/
          cp dist/*.zip artifacts/macOS/

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: |
            artifacts/macOS/*.dmg
            artifacts/macOS/*.zip
          if-no-files-found: error

  build-windows:
    name: Windows
    runs-on: windows-latest
    needs: build-mac
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Roaming\npm
          key: windows-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build Windows (unsigned)
        run: npm run dist:win
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: |
            dist/*.exe
            dist/*.zip
          if-no-files-found: error

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: build-mac
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: linux-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build Linux (unsigned)
        run: npm run dist:linux
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: |
            dist/*.AppImage
            dist/*.deb
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-mac
      - build-windows
      - build-linux
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Debug directory structure
        run: |
          echo "Artifacts directory contents:"
          ls -R artifacts

      - id: create_release
        name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Automated release for ${{ github.ref_name }}
          draft: false
          prerelease: false

      # macOS ARM assets
      - name: Find and Upload macOS ARM DMG
        run: |
          if ls artifacts/macOS/*mac.dmg 1> /dev/null 2>&1; then
            DMG_PATH=$(ls artifacts/macOS/*mac.dmg | grep -v intel | head -1)
            echo "Uploading $DMG_PATH"
            gh release upload ${{ github.ref_name }} "$DMG_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No macOS ARM DMG found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Upload macOS ARM ZIP
        run: |
          if ls artifacts/macOS/*mac.zip 1> /dev/null 2>&1; then
            ZIP_PATH=$(ls artifacts/macOS/*mac.zip | grep -v intel | head -1)
            echo "Uploading $ZIP_PATH"
            gh release upload ${{ github.ref_name }} "$ZIP_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No macOS ARM ZIP found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # macOS Intel assets
      - name: Find and Upload macOS Intel DMG
        run: |
          if ls artifacts/macOS/*mac-intel.dmg 1> /dev/null 2>&1; then
            DMG_PATH=$(ls artifacts/macOS/*mac-intel.dmg | head -1)
            echo "Uploading $DMG_PATH"
            gh release upload ${{ github.ref_name }} "$DMG_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No macOS Intel DMG found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Upload macOS Intel ZIP
        run: |
          if ls artifacts/macOS/*mac-intel.zip 1> /dev/null 2>&1; then
            ZIP_PATH=$(ls artifacts/macOS/*mac-intel.zip | head -1)
            echo "Uploading $ZIP_PATH"
            gh release upload ${{ github.ref_name }} "$ZIP_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No macOS Intel ZIP found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Windows
      - name: Find and Upload Windows EXE
        run: |
          if ls artifacts/Windows/*.exe 1> /dev/null 2>&1; then
            EXE_PATH=$(ls artifacts/Windows/*.exe | head -1)
            echo "Uploading $EXE_PATH"
            gh release upload ${{ github.ref_name }} "$EXE_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No Windows EXE found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Upload Windows ZIP
        run: |
          if ls artifacts/Windows/*.zip 1> /dev/null 2>&1; then
            ZIP_PATH=$(ls artifacts/Windows/*.zip | head -1)
            echo "Uploading $ZIP_PATH"
            gh release upload ${{ github.ref_name }} "$ZIP_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No Windows ZIP found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Linux
      - name: Find and Upload Linux AppImage
        run: |
          if ls artifacts/Linux/*.AppImage 1> /dev/null 2>&1; then
            APPIMAGE_PATH=$(ls artifacts/Linux/*.AppImage | head -1)
            echo "Uploading $APPIMAGE_PATH"
            gh release upload ${{ github.ref_name }} "$APPIMAGE_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No Linux AppImage found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Upload Linux DEB
        run: |
          if ls artifacts/Linux/*.deb 1> /dev/null 2>&1; then
            DEB_PATH=$(ls artifacts/Linux/*.deb | head -1)
            echo "Uploading $DEB_PATH"
            gh release upload ${{ github.ref_name }} "$DEB_PATH" --clobber --repo ${{ github.repository }}
          else
            echo "No Linux DEB found to upload"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
