name: Build, Sign, and Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 45  # Increased for notarization
    permissions:
      contents: write
    steps:
      # [Previous steps remain identical until build step]
      
      - name: Build application
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npm run build:macArm -- \
            --config.mac.identity="Austin Ginn (P76H6523Q4)" \
            --config.forceCodeSigning=true

      - name: Verify signature
        run: |
          codesign -dv --verbose=4 "./dist/mac-arm64/Wing to LiveTrax.app"
          spctl -a -vv "./dist/mac-arm64/Wing to LiveTrax.app" || true

      - name: Notarize application
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          # Package for notarization (must be zip)
          ditto -c -k --keepParent "./dist/mac-arm64/Wing to LiveTrax.app" "WingToLiveTrax.zip"
          
          # Submit to Apple (--wait pauses until completion)
          xcrun notarytool submit "WingToLiveTrax.zip" \
            --apple-id "$APPLE_ID" \
            --team-id "P76H6523Q4" \
            --password "$APPLE_ID_PASSWORD" \
            --wait

          # Staple the ticket to the app
          xcrun stapler staple "./dist/mac-arm64/Wing to LiveTrax.app"

      - name: Create final DMG
        run: |
          npm run build:macArm -- --config.mac.target=dmg

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npm run build:macArm -- --config.publish=github