# .github/workflows/release.yml
name: Build, Sign, and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  mac-release:
    runs-on: macos-latest
    timeout-minutes: 45
    permissions:
      contents: write

    steps:
      # 1) Checkout full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Node.js & cache npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      # 3) Import your code-signing cert
      - name: Import code-signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MAC_CERTIFICATE }}
          p12-password: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          keychain: build
          keychain-password: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}

      # 4) Build, sign, notarize & package
      - name: Build & Notarize macOS
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: P76H6523Q4
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          CSC_NAME: 'Austin Ginn (P76H6523Q4)'
        run: |
          npx electron-builder --mac --arm64 --publish=never

      # 5) Verify code-signing & notarization
      - name: Verify code-signing & notarization
        run: |
          codesign -dv --verbose=4 "dist/mac/Wing to LiveTrax.app"
          spctl -a -vv -t install "dist/mac/Wing to LiveTrax.app"
          xcrun stapler validate "dist/mac/Wing to LiveTrax.app"

      # 6) Upload DMG artifact
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wing-to-LiveTrax-macOS
          path: dist/*.dmg

      # 7) Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name:     ${{ github.ref_name }}
          files:    dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
