name: Build, Sign, and Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 45
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build:frontend

      - name: Clean keychains
        run: |
          security delete-keychain temp.keychain || true
          security list-keychains -d user -s login.keychain-db

      - name: Import signing certificate
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MAC_CERTIFICATE }}
          p12-password: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}

      - name: Build signed application
        run: |
          npx electron-builder --mac --arm64 \
            --config.mac.identity="Austin Ginn (P76H6523Q4)" \
            --config.forceCodeSigning=true \
            --config.mac.target=dir \
            --config.publish=never

      - name: Verify signature
        run: |
          codesign -dv --verbose=4 "./dist/mac-arm64/Wing to LiveTrax.app"
          spctl -a -vv "./dist/mac-arm64/Wing to LiveTrax.app" || true

      - name: Notarize application
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          ditto -c -k --keepParent "./dist/mac-arm64/Wing to LiveTrax.app" "WingToLiveTrax.zip"
          xcrun notarytool submit "WingToLiveTrax.zip" \
            --apple-id "$APPLE_ID" \
            --team-id "P76H6523Q4" \
            --password "$APPLE_ID_PASSWORD" \
            --wait
          xcrun stapler staple "./dist/mac-arm64/Wing to LiveTrax.app"

      - name: Create distributable DMG
        run: |
          npx electron-builder --mac --arm64 \
            --config.mac.target=dmg \
            --config.publish=never

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the version from package.json
          VERSION=$(node -p "require('./package.json').version")
          
          # Create release
          gh release create "v$VERSION" \
            "./dist/Wing to LiveTrax-$VERSION-arm64.dmg" \
            --title "v$VERSION" \
            --notes "Automatic release"