name: Build and Sign (macOS ARM64)

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build:frontend

      - name: Import signing certificate
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MAC_CERTIFICATE }}
          p12-password: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
          create-keychain: true

      - name: Build signed app (ARM64)
        run: |
          export ELECTRON_BUILDER_KEYCHAIN="temp.keychain"
          npm run build:macArm -- \
            --config.extraMetadata.name="wing-to-livetrax" \
            --config.mac.identity="Developer ID Application: Austin Ginn (P76H6523Q4)" \
            --config.afterSign="scripts/noop.js"

      - name: Verify signature
        run: |
          codesign -dv --verbose=4 "./dist/mac-arm64/Wing to LiveTrax.app"
          spctl -a -vv "./dist/mac-arm64/Wing to LiveTrax.app" || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wing-to-LiveTrax-macOS-ARM64
          path: ./dist/mac-arm64/Wing to LiveTrax.app