name: Build & Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm

      - run: npm ci

      - run: npm run build:frontend

      - name: Package App (all platforms)
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            macos-latest)   npm run build:mac   ;;
            windows-latest) npm run build:win   ;;
            ubuntu-latest)  npm run build:linux ;;
          esac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create / Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
            dist/*.deb
