name: Build & Publish Release

on:
  # Trigger on a pushed git tag like “v1.2.3”
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    # use a matrix so we run on each OS
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # we need tags

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Frontend build
        run: npm run build:frontend

      - name: Package app
        # on each runner pick the right script
        run: |
          case "${{ matrix.os }}" in
            macOS)   npm run build:mac   ;;
            Windows) npm run build:win   ;;
            Linux)   npm run build:linux ;;
          esac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        # softprops action will attach whatever is in electron-builder’s dist output
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
