name: Build & Publish Release

# trigger on a pushed tag like “v1.0.0”
on:
  push:
    tags:
      - 'v*.*.*'

# give the GITHUB_TOKEN permission to push tags, create releases, upload assets…
permissions:
  contents: write       # ← allow write access to repo contents (releases are under “contents”)
  packages: write       # ← if you also ever want to push packages
  id-token: write       # ← sometimes needed for OIDC but not strictly here

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js & deps
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm ci

      - name: Build Frontend
        run: npm run build:frontend

      - name: Package App
        run: |
          case "${{ matrix.os }}" in
            macos-latest)   npm run build:mac   ;;
            windows-latest) npm run build:win   ;;
            ubuntu-latest)  npm run build:linux ;;
          esac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create / Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/**/*   # adjust if your artifacts live somewhere else
